/* This file is auto-generated by opts.sh.  */

#include <intl.h>
#include "options.h"
#include "opts.h"

/* Set by -Wabi.
   Warn about things that will change when compiling with an ABI-compliant compiler  */
int warn_abi;

/* Set by -Waggregate-return.
   Warn about returning structures, unions or arrays  */
int warn_aggregate_return;

/* Set by -Wbad-function-cast.
   Warn about casting functions to incompatible types  */
int warn_bad_function_cast;

/* Set by -Wcast-align.
   Warn about pointer casts which increase alignment  */
int warn_cast_align;

/* Set by -Wcast-qual.
   Warn about casts which discard qualifiers  */
int warn_cast_qual;

/* Set by -Wchar-subscripts.
   Warn about subscripts whose type is \"char\"  */
int warn_char_subscripts;

/* Set by -Wconversion.
   Warn about possibly confusing type conversions  */
int warn_conversion;

/* Set by -Wctor-dtor-privacy.
   Warn when all constructors and destructors are private  */
int warn_ctor_dtor_privacy;

/* Set by -Wdeclaration-after-statement.
   Warn when a declaration is found after a statement  */
int warn_declaration_after_statement;

/* Set by -Wdeprecated.
   Warn about deprecated compiler features  */
int warn_deprecated = 1;

/* Set by -Wdeprecated-declarations.
   Warn about uses of __attribute__((deprecated)) declarations  */
int warn_deprecated_decl = 1;

/* Set by -Wdisabled-optimization.
   Warn when an optimization pass is disabled  */
int warn_disabled_optimization;

/* Set by -Wdiv-by-zero.
   Warn about compile-time integer division by zero  */
int warn_div_by_zero = 1;

/* Set by -Weffc++.
   Warn about violations of Effective C++ style rules  */
int warn_ecpp;

/* Set by -Werror.
   Treat all warnings as errors  */
int warnings_are_errors;

/* Set by -Wfatal-errors.
   Exit on the first error occurred  */
int flag_fatal_errors;

/* Set by -Wfloat-equal.
   Warn if testing floating point numbers for equality  */
int warn_float_equal;

/* Set by -Wformat-extra-args.
   Warn if passing too many arguments to a function for its format string  */
int warn_format_extra_args;

/* Set by -Wformat-nonliteral.
   Warn about format strings that are not literals  */
int warn_format_nonliteral;

/* Set by -Wformat-security.
   Warn about possible security problems with format functions  */
int warn_format_security;

/* Set by -Wformat-y2k.
   Warn about strftime formats yielding 2-digit years  */
int warn_format_y2k;

/* Set by -Wformat-zero-length.
   Warn about zero-length formats  */
int warn_format_zero_length;

/* Set by -Wimplicit-function-declaration.
   Warn about implicit function declarations  */
int mesg_implicit_function_declaration = -1;

/* Set by -Wimplicit-int.
   Warn when a declaration does not specify a type  */
int warn_implicit_int;

/* Set by -Winit-self.
   Warn about variables which are initialized to themselves.  */
int warn_init_self;

/* Set by -Winline.
   Warn when an inlined function cannot be inlined  */
int warn_inline;

/* Set by -Winvalid-offsetof.
   Warn about invalid uses of the \"offsetof\" macro  */
int warn_invalid_offsetof = 1;

/* Set by -Wlong-long.
   Do not warn about using \"long long\" when -pedantic  */
int warn_long_long = 1;

/* Set by -Wmissing-braces.
   Warn about possibly missing braces around initializers  */
int warn_missing_braces;

/* Set by -Wmissing-declarations.
   Warn about global functions without previous declarations  */
int warn_missing_declarations;

/* Set by -Wmissing-field-initializers.
   Warn about missing fields in struct initializers  */
int warn_missing_field_initializers = -1;

/* Set by -Wmissing-format-attribute.
   Warn about functions which might be candidates for format attributes  */
int warn_missing_format_attribute;

/* Set by -Wmissing-noreturn.
   Warn about functions which might be candidates for __attribute__((noreturn))  */
int warn_missing_noreturn;

/* Set by -Wmissing-prototypes.
   Warn about global functions without prototypes  */
int warn_missing_prototypes;

/* Set by -Wnested-externs.
   Warn about \"extern\" declarations not at file scope  */
int warn_nested_externs;

/* Set by -Wnon-template-friend.
   Warn when non-templatized friend functions are declared within a template  */
int warn_nontemplate_friend = 1;

/* Set by -Wnon-virtual-dtor.
   Warn about non-virtual destructors  */
int warn_nonvdtor;

/* Set by -Wnonnull.
   Warn about NULL being passed to argument slots marked as requiring non-NULL  */
int warn_nonnull;

/* Set by -Wold-style-cast.
   Warn if a C-style cast is used in a program  */
int warn_old_style_cast;

/* Set by -Wold-style-definition.
   Warn if an old-style parameter definition is used  */
int warn_old_style_definition;

/* Set by -Woverloaded-virtual.
   Warn about overloaded virtual function names  */
int warn_overloaded_virtual;

/* Set by -Wpacked.
   Warn when the packed attribute has no effect on struct layout  */
int warn_packed;

/* Set by -Wpadded.
   Warn when padding is required to align structure members  */
int warn_padded;

/* Set by -Wparentheses.
   Warn about possibly missing parentheses  */
int warn_parentheses;

/* Set by -Wpmf-conversions.
   Warn when converting the type of pointers to member functions  */
int warn_pmf2ptr = 1;

/* Set by -Wpointer-arith.
   Warn about function pointer arithmetic  */
int warn_pointer_arith;

/* Set by -Wpointer-sign.
   Warn when a pointer differs in signedness in an assignment.  */
int warn_pointer_sign = 1;

/* Set by -Wprotocol.
   Warn if inherited methods are unimplemented  */
int warn_protocol = 1;

/* Set by -Wredundant-decls.
   Warn about multiple declarations of the same object  */
int warn_redundant_decls;

/* Set by -Wreorder.
   Warn when the compiler reorders code  */
int warn_reorder;

/* Set by -Wselector.
   Warn if a selector has multiple methods  */
int warn_selector;

/* Set by -Wsequence-point.
   Warn about possible violations of sequence point rules  */
int warn_sequence_point;

/* Set by -Wshadow.
   Warn when one local variable shadows another  */
int warn_shadow;

/* Set by -Wsign-compare.
   Warn about signed-unsigned comparisons  */
int warn_sign_compare = -1;

/* Set by -Wsign-promo.
   Warn when overload promotes from unsigned to signed  */
int warn_sign_promo;

/* Set by -Wstrict-prototypes.
   Warn about unprototyped function declarations  */
int warn_strict_prototypes;

/* Set by -Wswitch.
   Warn about enumerated switches, with no default, missing a case  */
int warn_switch;

/* Set by -Wswitch-default.
   Warn about enumerated switches missing a \"default:\" statement  */
int warn_switch_default;

/* Set by -Wswitch-enum.
   Warn about all enumerated switches missing a specific case  */
int warn_switch_enum;

/* Set by -Wsynth.
   Warn when synthesis behavior differs from Cfront  */
int warn_synth;

/* Set by -Wsystem-headers.
   Do not suppress warnings from system headers  */
int warn_system_headers;

/* Set by -Wtraditional.
   Warn about features not present in traditional C  */
int warn_traditional;

/* Set by -Wundeclared-selector.
   Warn about @selector()s without previously declared methods  */
int warn_undeclared_selector;

/* Set by -Wuninitialized.
   Warn about uninitialized automatic variables  */
int warn_uninitialized;

/* Set by -Wunreachable-code.
   Warn about code that will never be executed  */
int warn_notreached;

/* Set by -Wunused-function.
   Warn when a function is unused  */
int warn_unused_function;

/* Set by -Wunused-label.
   Warn when a label is unused  */
int warn_unused_label;

/* Set by -Wunused-parameter.
   Warn when a function parameter is unused  */
int warn_unused_parameter;

/* Set by -Wunused-value.
   Warn when an expression value is unused  */
int warn_unused_value;

/* Set by -Wunused-variable.
   Warn when a variable is unused  */
int warn_unused_variable;

/* Set by -fPIC.
   Generate position-independent code if possible (large mode)  */
int flag_pic;

/* Set by -fPIE.
   Generate position-independent code for executables if possible (large mode)  */
int flag_pie;

/* Set by -fabi-version=.
     */
int flag_abi_version = 2;

/* Set by -falign-functions.
   Align the start of functions  */
int align_functions;

/* Set by -falign-jumps.
   Align labels which are only reached by jumping  */
int align_jumps;

/* Set by -falign-labels.
   Align all labels  */
int align_labels;

/* Set by -falign-loops.
   Align the start of loops  */
int align_loops;

/* Set by -fargument-alias.
   Specify that arguments may alias each other and globals  */
int flag_argument_noalias;

/* Set by -fasynchronous-unwind-tables.
   Generate unwind tables that are exact at each instruction boundary  */
int flag_asynchronous_unwind_tables;

/* Set by -fbounds-check.
   Generate code to check bounds before indexing arrays  */
int flag_bounds_check;

/* Set by -fbranch-count-reg.
   Replace add, compare, branch with branch on count register  */
int flag_branch_on_count_reg = 1;

/* Set by -fbranch-probabilities.
   Use profiling information for branch probabilities  */
int flag_branch_probabilities;

/* Set by -fbranch-target-load-optimize.
   Perform branch target load optimization before prologue / epilogue threading  */
int flag_branch_target_load_optimize;

/* Set by -fbranch-target-load-optimize2.
   Perform branch target load optimization after prologue / epilogue threading  */
int flag_branch_target_load_optimize2;

/* Set by -fbtr-bb-exclusive.
   Restrict target load migration not to re-use registers in any basic block  */
int flag_btr_bb_exclusive;

/* Set by -fcaller-saves.
   Save registers around function calls  */
int flag_caller_saves;

/* Set by -fcommon.
   Do not put uninitialized globals in the common section  */
int flag_no_common;

/* Set by -fcprop-registers.
   Perform a register copy-propagation optimization pass  */
int flag_cprop_registers;

/* Set by -fcrossjumping.
   Perform cross-jumping optimization  */
int flag_crossjumping;

/* Set by -fcse-follow-jumps.
   When running CSE, follow jumps to their targets  */
int flag_cse_follow_jumps;

/* Set by -fcse-skip-blocks.
   When running CSE, follow conditional jumps  */
int flag_cse_skip_blocks;

/* Set by -fcx-limited-range.
   Omit range reduction step when performing complex division  */
int flag_cx_limited_range;

/* Set by -fdata-sections.
   Place data items into their own section  */
int flag_data_sections;

/* Set by -fdefer-pop.
   Defer popping functions args from stack until later  */
int flag_defer_pop;

/* Set by -fdelayed-branch.
   Attempt to fill delay slots of branch instructions  */
int flag_delayed_branch;

/* Set by -fdelete-null-pointer-checks.
   Delete useless null pointer checks  */
int flag_delete_null_pointer_checks;

/* Set by -feliminate-dwarf2-dups.
   Perform DWARF2 duplicate elimination  */
int flag_eliminate_dwarf2_dups;

/* Set by -feliminate-unused-debug-symbols.
   Perform unused type elimination in debug info  */
int flag_debug_only_used_symbols;

/* Set by -feliminate-unused-debug-types.
   Perform unused type elimination in debug info  */
int flag_eliminate_unused_debug_types = 1;

/* Set by -fexceptions.
   Enable exception handling  */
int flag_exceptions;

/* Set by -fexpensive-optimizations.
   Perform a number of minor, expensive optimizations  */
int flag_expensive_optimizations;

/* Set by -ffinite-math-only.
   Assume no NaNs or infinities are generated  */
int flag_finite_math_only;

/* Set by -ffloat-store.
   Don't allocate floats and doubles in extended-precision registers  */
int flag_float_store;

/* Set by -fforce-addr.
   Copy memory address constants into registers before use  */
int flag_force_addr;

/* Set by -fforce-mem.
   Copy memory operands into registers before use  */
int flag_force_mem;

/* Set by -ffunction-cse.
   Allow function addresses to be held in registers  */
int flag_no_function_cse;

/* Set by -ffunction-sections.
   Place each function into its own section  */
int flag_function_sections;

/* Set by -fgcse.
   Perform global common subexpression elimination  */
int flag_gcse;

/* Set by -fgcse-after-reload.
   Perform global common subexpression elimination after register allocation  */
int flag_gcse_after_reload;

/* Set by -fgcse-las.
   Perform redundant load after store elimination in global common subexpression  */
int flag_gcse_las = 0;

/* Set by -fgcse-lm.
   Perform enhanced load motion during global common subexpression elimination  */
int flag_gcse_lm = 1;

/* Set by -fgcse-sm.
   Perform store motion after global common subexpression elimination  */
int flag_gcse_sm = 0;

/* Set by -fguess-branch-probability.
   Enable guessing of branch probabilities  */
int flag_guess_branch_prob;

/* Set by -fident.
   Process #ident directives  */
int flag_no_ident;

/* Set by -fif-conversion.
   Perform conversion of conditional jumps to branchless equivalents  */
int flag_if_conversion;

/* Set by -fif-conversion2.
   Perform conversion of conditional jumps to conditional execution  */
int flag_if_conversion2;

/* Set by -finhibit-size-directive.
   Do not generate .size directives  */
int flag_inhibit_size_directive;

/* Set by -finline.
   Pay attention to the \"inline\" keyword  */
int flag_no_inline = 2;

/* Set by -finline-functions.
   Integrate simple functions into their callers  */
int flag_inline_functions;

/* Set by -finline-functions-called-once.
   Integrate functions called once into their callers  */
int flag_inline_functions_called_once = 1;

/* Set by -finstrument-functions.
   Instrument function entry and exit with profiling calls  */
int flag_instrument_function_entry_exit;

/* Set by -fivopts.
   Optimize induction variables on trees  */
int flag_ivopts = 1;

/* Set by -fkeep-inline-functions.
   Generate code for functions even if they are fully inlined  */
int flag_keep_inline_functions;

/* Set by -fkeep-static-consts.
   Emit static const variables even if they are not used  */
int flag_keep_static_consts = 1;

/* Set by -fleading-underscore.
   Give external symbols a leading underscore  */
int flag_leading_underscore = -1;

/* Set by -floop-optimize.
   Perform loop optimizations  */
int flag_loop_optimize;

/* Set by -floop-optimize2.
   Perform loop optimizations using the new loop optimizer  */
int flag_loop_optimize2;

/* Set by -fmath-errno.
   Set errno after built-in math functions  */
int flag_errno_math = 1;

/* Set by -fmem-report.
   Report on permanent memory allocation  */
int mem_report;

/* Set by -fmerge-all-constants.
   Attempt to merge identical constants and constant variables  */
int flag_merge_constants = 1;

/* Set by -fmodulo-sched.
   Perform SMS based modulo scheduling before the first scheduling pass  */
int flag_modulo_sched;

/* Set by -fmove-loop-invariants.
   Move loop invariant computations out of loops  */
int flag_move_loop_invariants;

/* Set by -fmudflap.
   Add mudflap bounds-checking instrumentation for single-threaded program.  */
int flag_mudflap;

/* Set by -fmudflapir.
   Ignore read operations when inserting mudflap instrumentation.  */
int flag_mudflap_ignore_reads;

/* Set by -fmudflapth.
   Add mudflap bounds-checking instrumentation for multi-threaded program.  */
int flag_mudflap_threads;

/* Set by -fnon-call-exceptions.
   Support synchronous non-call exceptions  */
int flag_non_call_exceptions;

/* Set by -fomit-frame-pointer.
   When possible do not generate stack frames  */
int flag_omit_frame_pointer;

/* Set by -foptimize-register-move.
   Do the full register move optimization pass  */
int flag_regmove;

/* Set by -foptimize-sibling-calls.
   Optimize sibling and tail recursive calls  */
int flag_optimize_sibling_calls;

/* Set by -fpack-struct.
   Pack structure members together without holes  */
int flag_pack_struct;

/* Set by -fpeel-loops.
   Perform loop peeling  */
int flag_peel_loops;

/* Set by -fpeephole.
   Enable machine specific peephole optimizations  */
int flag_no_peephole;

/* Set by -fpeephole2.
   Enable an RTL peephole pass before sched2  */
int flag_peephole2;

/* Set by -fprefetch-loop-arrays.
   Generate prefetch instructions, if available, for arrays in loops  */
int flag_prefetch_loop_arrays;

/* Set by -fprofile.
   Enable basic program profiling code  */
int profile_flag;

/* Set by -fprofile-arcs.
   Insert arc-based program profiling code  */
int profile_arc_flag;

/* Set by -fprofile-values.
   Insert code to profile values of expressions  */
int flag_profile_values;

/* Set by -fregmove.
   Enables a register move optimization  */
int flag_regmove;

/* Set by -frename-registers.
   Perform a register renaming optimization pass  */
int flag_rename_registers;

/* Set by -freorder-blocks.
   Reorder basic blocks to improve code placement  */
int flag_reorder_blocks;

/* Set by -freorder-blocks-and-partition.
   Reorder basic blocks and partition into hot and cold sections  */
int flag_reorder_blocks_and_partition;

/* Set by -freorder-functions.
   Reorder functions to improve code placement  */
int flag_reorder_functions;

/* Set by -frerun-cse-after-loop.
   Add a common subexpression elimination pass after loop optimizations  */
int flag_rerun_cse_after_loop;

/* Set by -frerun-loop-opt.
   Run the loop optimizer twice  */
int flag_rerun_loop_opt;

/* Set by -freschedule-modulo-scheduled-loops.
   Enable/Disable the traditional scheduling in loops that already passed modulo scheduling  */
int flag_resched_modulo_sched;

/* Set by -frounding-math.
   Disable optimizations that assume default FP rounding behavior  */
int flag_rounding_math;

/* Set by -fsched-interblock.
   Enable scheduling across basic blocks  */
int flag_schedule_interblock = 1;

/* Set by -fsched-spec.
   Allow speculative motion of non-loads  */
int flag_schedule_speculative = 1;

/* Set by -fsched-spec-load.
   Allow speculative motion of some loads  */
int flag_schedule_speculative_load;

/* Set by -fsched-spec-load-dangerous.
   Allow speculative motion of more loads  */
int flag_schedule_speculative_load_dangerous;

/* Set by -fsched-stalled-insns.
   Allow premature scheduling of queued insns  */
int flag_sched_stalled_insns;

/* Set by -fsched-stalled-insns-dep.
   Set dependence distance checking in premature scheduling of queued insns  */
int flag_sched_stalled_insns_dep = 1;

/* Set by -fsched2-use-superblocks.
   If scheduling post reload, do superblock scheduling  */
int flag_sched2_use_superblocks;

/* Set by -fsched2-use-traces.
   If scheduling post reload, do trace scheduling  */
int flag_sched2_use_traces;

/* Set by -fschedule-insns.
   Reschedule instructions before register allocation  */
int flag_schedule_insns;

/* Set by -fschedule-insns2.
   Reschedule instructions after register allocation  */
int flag_schedule_insns_after_reload;

/* Set by -fshared-data.
   Mark data as shared rather than private  */
int flag_shared_data;

/* Set by -fsignaling-nans.
   Disable optimizations observable by IEEE signaling NaNs  */
int flag_signaling_nans;

/* Set by -fsingle-precision-constant.
   Convert floating point constants to single precision constants  */
int flag_single_precision_constant;

/* Set by -fspeculative-prefetching.
   Use value profiling for speculative prefetching  */
int flag_speculative_prefetching;

/* Set by -fsplit-ivs-in-unroller.
   Split lifetimes of induction variables when loops are unrolled.  */
int flag_split_ivs_in_unroller = 1;

/* Set by -fstack-check.
   Insert stack checking code into the program  */
int flag_stack_check;

/* Set by -fstrength-reduce.
   Perform strength reduction optimizations  */
int flag_strength_reduce;

/* Set by -fstrict-aliasing.
   Assume strict aliasing rules apply  */
int flag_strict_aliasing;

/* Set by -fsyntax-only.
   Check for syntax errors, then stop  */
int flag_syntax_only;

/* Set by -ftest-coverage.
   Create data files needed by \"gcov\"  */
int flag_test_coverage;

/* Set by -fthread-jumps.
   Perform jump threading optimizations  */
int flag_thread_jumps;

/* Set by -ftime-report.
   Report the time taken by each compiler pass  */
int time_report;

/* Set by -ftracer.
   Perform superblock formation via tail duplication  */
int flag_tracer;

/* Set by -ftrapping-math.
   Assume floating-point operations can trap  */
int flag_trapping_math = 1;

/* Set by -ftrapv.
   Trap for signed overflow in addition, subtraction and multiplication  */
int flag_trapv;

/* Set by -ftree-based-profiling.
   Use tree-ssa based implementation of profiling  */
int flag_tree_based_profiling;

/* Set by -ftree-ccp.
   Enable SSA-CCP optimization on trees  */
int flag_tree_ccp;

/* Set by -ftree-ch.
   Enable loop header copying on trees  */
int flag_tree_ch;

/* Set by -ftree-combine-temps.
   Coalesce memory temporaries in the SSA->normal pass  */
int flag_tree_combine_temps;

/* Set by -ftree-copyrename.
   Replace SSA temporaries with better names in copies.  */
int flag_tree_copyrename;

/* Set by -ftree-dce.
   Enable SSA dead code elimination optimization on trees  */
int flag_tree_dce;

/* Set by -ftree-dominator-opts.
   Enable dominator optimizations  */
int flag_tree_dom;

/* Set by -ftree-dse.
   Enable dead store elimination  */
int flag_tree_dse;

/* Set by -ftree-fre.
   Enable Full Redundancy Elimination (FRE) on trees  */
int flag_tree_fre;

/* Set by -ftree-loop-im.
   Enable loop invariant motion on trees  */
int flag_tree_loop_im = 1;

/* Set by -ftree-loop-ivcanon.
   Create canonical induction variables in loops  */
int flag_tree_loop_ivcanon = 1;

/* Set by -ftree-loop-linear.
   Enable linear loop transforms on trees  */
int flag_tree_loop_linear;

/* Set by -ftree-loop-optimize.
   Enable loop optimizations on tree level  */
int flag_tree_loop_optimize = 1;

/* Set by -ftree-lrs.
   Perform live range splitting during the SSA->normal pass.  */
int flag_tree_live_range_split;

/* Set by -ftree-pre.
   Enable SSA-PRE optimization on trees  */
int flag_tree_pre;

/* Set by -ftree-sra.
   Perform scalar replacement of aggregates  */
int flag_tree_sra;

/* Set by -ftree-ter.
   Replace temporary expressions in the SSA->normal pass  */
int flag_tree_ter;

/* Set by -ftree-vectorize.
   Enable loop vectorization on trees  */
int flag_tree_vectorize;

/* Set by -funit-at-a-time.
   Compile whole compilation unit at a time  */
int flag_unit_at_a_time;

/* Set by -funroll-all-loops.
   Perform loop unrolling for all loops  */
int flag_unroll_all_loops;

/* Set by -funroll-loops.
   Perform loop unrolling when iteration count is known  */
int flag_unroll_loops;

/* Set by -funsafe-math-optimizations.
   Allow math optimizations that may violate IEEE or ISO standards  */
int flag_unsafe_math_optimizations;

/* Set by -funswitch-loops.
   Perform loop unswitching  */
int flag_unswitch_loops;

/* Set by -funwind-tables.
   Just generate unwind tables for exception handling  */
int flag_unwind_tables;

/* Set by -fvariable-expansion-in-unroller.
   Apply variable expansion when loops are unrolled.  */
int flag_variable_expansion_in_unroller;

/* Set by -fverbose-asm.
   Add extra commentary to assembler output  */
int flag_verbose_asm;

/* Set by -fvpt.
   Use expression value profiles in optimizations  */
int flag_value_profile_transformations;

/* Set by -fweb.
   Construct webs and split unrelated uses of single variable  */
int flag_web = 0;

/* Set by -fwrapv.
   Assume signed arithmetic overflow wraps around  */
int flag_wrapv;

/* Set by -fzero-initialized-in-bss.
   Put zero initialized data in the bss section  */
int flag_zero_initialized_in_bss = 1;

/* Set by -p.
   Enable function profiling  */
int profile_flag;

/* Set by -pedantic.
   Issue warnings needed for strict compliance to the standard  */
int pedantic;

/* Set by -quiet.
   Do not display functions compiled or elapsed time  */
int quiet_flag;

/* Set by -version.
   Display the compiler's version  */
int version_flag;

/* Set by -w.
   Suppress warnings  */
int inhibit_warnings;

const char * const lang_names[] =
{
  "C",
  "C++",
  "ObjC",
  "ObjC++",
  0
};

const unsigned int cl_options_count = N_OPTS;

const struct cl_option cl_options[] =
{
  { "--help",
    N_("Display this information"),
    N_OPTS, 5, CL_COMMON, 0, 0, 0 },
  { "--output-pch=",
    0,
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "--param",
    N_("--param <param>=<value>	Set parameter <param> to value.  See below for a complete list of parameters"),
    N_OPTS, 6, CL_COMMON | CL_SEPARATE, 0, 0, 0 },
  { "--target-help",
    0,
    N_OPTS, 12, CL_COMMON, 0, 0, 0 },
  { "--version",
    0,
    N_OPTS, 8, CL_COMMON, 0, 0, 0 },
  { "-A",
    N_("-A<question>=<answer>	Assert the <answer> to <question>.  Putting '-' before <question> disables the <answer> to <question>"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-C",
    N_("Do not discard comments"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-CC",
    N_("Do not discard comments in macro expansions"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-D",
    N_("-D<macro>[=<val>]	Define a <macro> with <val> as its value.  If just <macro> is given, <val> is taken to be 1"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-E",
    0,
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_UNDOCUMENTED, 0, 0, 0 },
  { "-F",
    N_("-F <dir>	Add <dir> to the end of the main framework include path"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-G",
    N_("-G<number>	Put global and static data smaller than <number> bytes into a special section (on some targets)"),
    N_OPTS, 1, CL_COMMON | CL_JOINED | CL_SEPARATE | CL_UINTEGER, 0, 0, 0 },
  { "-H",
    N_("Print the name of header files as they are used"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-I",
    N_("-I <dir>	Add <dir> to the end of the main include path"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-M",
    N_("Generate make dependencies"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-MD",
    N_("Generate make dependencies and compile"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_SEPARATE, 0, 0, 0 },
  { "-MF",
    N_("-MF <file>	Write dependency output to the given file"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-MG",
    N_("Treat missing header files as generated files"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-MM",
    N_("Like -M but ignore system header files"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-MMD",
    N_("Like -MD but ignore system header files"),
    N_OPTS, 3, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_SEPARATE, 0, 0, 0 },
  { "-MP",
    N_("Generate phony targets for all headers"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-MQ",
    N_("-MQ <target>	Add a MAKE-quoted target"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-MT",
    N_("-MT <target>	Add an unquoted target"),
    N_OPTS, 2, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-O",
    N_("-O<number>	Set optimization level to <number>"),
    N_OPTS, 1, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-Os",
    N_("Optimize for space rather than speed"),
    OPT_O, 2, CL_COMMON, 0, 0, 0 },
  { "-P",
    N_("Do not generate #line directives"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-U",
    N_("-U<macro>	Undefine <macro>"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-W",
    N_("This switch is deprecated; use -Wextra instead"),
    N_OPTS, 1, CL_COMMON | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-Wabi",
    N_("Warn about things that will change when compiling with an ABI-compliant compiler"),
    N_OPTS, 4, CL_CXX | CL_ObjCXX, &warn_abi, 0, 0 },
  { "-Waggregate-return",
    N_("Warn about returning structures, unions or arrays"),
    N_OPTS, 17, CL_COMMON, &warn_aggregate_return, 0, 0 },
  { "-Wall",
    N_("Enable most warning messages"),
    N_OPTS, 4, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wbad-function-cast",
    N_("Warn about casting functions to incompatible types"),
    N_OPTS, 18, CL_C | CL_ObjC, &warn_bad_function_cast, 0, 0 },
  { "-Wcast-align",
    N_("Warn about pointer casts which increase alignment"),
    N_OPTS, 11, CL_COMMON, &warn_cast_align, 0, 0 },
  { "-Wcast-qual",
    N_("Warn about casts which discard qualifiers"),
    N_OPTS, 10, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_cast_qual, 0, 0 },
  { "-Wchar-subscripts",
    N_("Warn about subscripts whose type is \"char\""),
    N_OPTS, 16, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_char_subscripts, 0, 0 },
  { "-Wcomment",
    N_("Warn about possibly nested block comments, and C++ comments spanning more than one physical line"),
    N_OPTS, 8, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wcomments",
    N_("Synonym for -Wcomment"),
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wconversion",
    N_("Warn about possibly confusing type conversions"),
    N_OPTS, 11, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_conversion, 0, 0 },
  { "-Wctor-dtor-privacy",
    N_("Warn when all constructors and destructors are private"),
    N_OPTS, 18, CL_CXX | CL_ObjCXX, &warn_ctor_dtor_privacy, 0, 0 },
  { "-Wdeclaration-after-statement",
    N_("Warn when a declaration is found after a statement"),
    N_OPTS, 28, CL_C | CL_ObjC, &warn_declaration_after_statement, 0, 0 },
  { "-Wdeprecated",
    N_("Warn about deprecated compiler features"),
    N_OPTS, 11, CL_CXX | CL_ObjCXX, &warn_deprecated, 0, 0 },
  { "-Wdeprecated-declarations",
    N_("Warn about uses of __attribute__((deprecated)) declarations"),
    N_OPTS, 24, CL_COMMON, &warn_deprecated_decl, 0, 0 },
  { "-Wdisabled-optimization",
    N_("Warn when an optimization pass is disabled"),
    N_OPTS, 22, CL_COMMON, &warn_disabled_optimization, 0, 0 },
  { "-Wdiv-by-zero",
    N_("Warn about compile-time integer division by zero"),
    N_OPTS, 12, CL_C | CL_ObjC, &warn_div_by_zero, 0, 0 },
  { "-Weffc++",
    N_("Warn about violations of Effective C++ style rules"),
    N_OPTS, 7, CL_CXX | CL_ObjCXX, &warn_ecpp, 0, 0 },
  { "-Wendif-labels",
    N_("Warn about stray tokens after #elif and #endif"),
    N_OPTS, 13, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Werror",
    N_("Treat all warnings as errors"),
    N_OPTS, 6, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_COMMON, &warnings_are_errors, 0, 0 },
  { "-Werror-implicit-function-declaration",
    N_("Make implicit function declarations an error"),
    N_OPTS, 36, CL_C | CL_ObjC | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-Wextra",
    N_("Print extra (possibly unwanted) warnings"),
    N_OPTS, 6, CL_COMMON, 0, 0, 0 },
  { "-Wfatal-errors",
    N_("Exit on the first error occurred"),
    N_OPTS, 13, CL_COMMON, &flag_fatal_errors, 0, 0 },
  { "-Wfloat-equal",
    N_("Warn if testing floating point numbers for equality"),
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_float_equal, 0, 0 },
  { "-Wformat",
    N_("Warn about printf/scanf/strftime/strfmon format string anomalies"),
    N_OPTS, 7, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wformat-extra-args",
    N_("Warn if passing too many arguments to a function for its format string"),
    N_OPTS, 18, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_format_extra_args, 0, 0 },
  { "-Wformat-nonliteral",
    N_("Warn about format strings that are not literals"),
    N_OPTS, 18, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_format_nonliteral, 0, 0 },
  { "-Wformat-security",
    N_("Warn about possible security problems with format functions"),
    N_OPTS, 16, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_format_security, 0, 0 },
  { "-Wformat-y2k",
    N_("Warn about strftime formats yielding 2-digit years"),
    N_OPTS, 11, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_format_y2k, 0, 0 },
  { "-Wformat-zero-length",
    N_("Warn about zero-length formats"),
    N_OPTS, 19, CL_C | CL_ObjC, &warn_format_zero_length, 0, 0 },
  { "-Wformat=",
    0,
    N_OPTS, 8, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED, 0, 0, 0 },
  { "-Wimplicit",
    0,
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wimplicit-function-declaration",
    N_("Warn about implicit function declarations"),
    N_OPTS, 30, CL_C | CL_ObjC, &mesg_implicit_function_declaration, 0, 0 },
  { "-Wimplicit-int",
    N_("Warn when a declaration does not specify a type"),
    N_OPTS, 13, CL_C | CL_ObjC, &warn_implicit_int, 0, 0 },
  { "-Wimport",
    N_("Deprecated.  This switch has no effect."),
    N_OPTS, 7, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Winit-self",
    N_("Warn about variables which are initialized to themselves."),
    N_OPTS, 10, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_init_self, 0, 0 },
  { "-Winline",
    N_("Warn when an inlined function cannot be inlined"),
    N_OPTS, 7, CL_COMMON, &warn_inline, 0, 0 },
  { "-Winvalid-offsetof",
    N_("Warn about invalid uses of the \"offsetof\" macro"),
    N_OPTS, 17, CL_CXX | CL_ObjCXX, &warn_invalid_offsetof, 0, 0 },
  { "-Winvalid-pch",
    N_("Warn about PCH files that are found but not used"),
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wlarger-than-",
    N_("-Wlarger-than-<number>	Warn if an object is larger than <number> bytes"),
    N_OPTS, 13, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-Wlong-long",
    N_("Do not warn about using \"long long\" when -pedantic"),
    N_OPTS, 10, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_long_long, 0, 0 },
  { "-Wmain",
    N_("Warn about suspicious declarations of \"main\""),
    N_OPTS, 5, CL_C | CL_ObjC, 0, 0, 0 },
  { "-Wmissing-braces",
    N_("Warn about possibly missing braces around initializers"),
    N_OPTS, 15, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_missing_braces, 0, 0 },
  { "-Wmissing-declarations",
    N_("Warn about global functions without previous declarations"),
    N_OPTS, 21, CL_C | CL_ObjC, &warn_missing_declarations, 0, 0 },
  { "-Wmissing-field-initializers",
    N_("Warn about missing fields in struct initializers"),
    N_OPTS, 27, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_missing_field_initializers, 0, 0 },
  { "-Wmissing-format-attribute",
    N_("Warn about functions which might be candidates for format attributes"),
    N_OPTS, 25, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_missing_format_attribute, 0, 0 },
  { "-Wmissing-include-dirs",
    N_("Warn about user-specified include directories that do not exist"),
    N_OPTS, 21, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wmissing-noreturn",
    N_("Warn about functions which might be candidates for __attribute__((noreturn))"),
    N_OPTS, 17, CL_COMMON, &warn_missing_noreturn, 0, 0 },
  { "-Wmissing-prototypes",
    N_("Warn about global functions without prototypes"),
    N_OPTS, 19, CL_C | CL_ObjC, &warn_missing_prototypes, 0, 0 },
  { "-Wmultichar",
    N_("Warn about use of multi-character character constants"),
    N_OPTS, 10, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wnested-externs",
    N_("Warn about \"extern\" declarations not at file scope"),
    N_OPTS, 15, CL_C | CL_ObjC, &warn_nested_externs, 0, 0 },
  { "-Wnon-template-friend",
    N_("Warn when non-templatized friend functions are declared within a template"),
    N_OPTS, 20, CL_CXX | CL_ObjCXX, &warn_nontemplate_friend, 0, 0 },
  { "-Wnon-virtual-dtor",
    N_("Warn about non-virtual destructors"),
    N_OPTS, 17, CL_CXX | CL_ObjCXX, &warn_nonvdtor, 0, 0 },
  { "-Wnonnull",
    N_("Warn about NULL being passed to argument slots marked as requiring non-NULL"),
    N_OPTS, 8, CL_C | CL_ObjC, &warn_nonnull, 0, 0 },
  { "-Wold-style-cast",
    N_("Warn if a C-style cast is used in a program"),
    N_OPTS, 15, CL_CXX | CL_ObjCXX, &warn_old_style_cast, 0, 0 },
  { "-Wold-style-definition",
    N_("Warn if an old-style parameter definition is used"),
    N_OPTS, 21, CL_C | CL_ObjC, &warn_old_style_definition, 0, 0 },
  { "-Woverloaded-virtual",
    N_("Warn about overloaded virtual function names"),
    N_OPTS, 19, CL_CXX | CL_ObjCXX, &warn_overloaded_virtual, 0, 0 },
  { "-Wpacked",
    N_("Warn when the packed attribute has no effect on struct layout"),
    N_OPTS, 7, CL_COMMON, &warn_packed, 0, 0 },
  { "-Wpadded",
    N_("Warn when padding is required to align structure members"),
    N_OPTS, 7, CL_COMMON, &warn_padded, 0, 0 },
  { "-Wparentheses",
    N_("Warn about possibly missing parentheses"),
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_parentheses, 0, 0 },
  { "-Wpmf-conversions",
    N_("Warn when converting the type of pointers to member functions"),
    N_OPTS, 16, CL_CXX | CL_ObjCXX, &warn_pmf2ptr, 0, 0 },
  { "-Wpointer-arith",
    N_("Warn about function pointer arithmetic"),
    N_OPTS, 14, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_pointer_arith, 0, 0 },
  { "-Wpointer-sign",
    N_("Warn when a pointer differs in signedness in an assignment."),
    N_OPTS, 13, CL_C | CL_ObjC, &warn_pointer_sign, 0, 0 },
  { "-Wprotocol",
    N_("Warn if inherited methods are unimplemented"),
    N_OPTS, 9, CL_ObjC | CL_ObjCXX, &warn_protocol, 0, 0 },
  { "-Wredundant-decls",
    N_("Warn about multiple declarations of the same object"),
    N_OPTS, 16, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_redundant_decls, 0, 0 },
  { "-Wreorder",
    N_("Warn when the compiler reorders code"),
    N_OPTS, 8, CL_CXX | CL_ObjCXX, &warn_reorder, 0, 0 },
  { "-Wreturn-type",
    N_("Warn whenever a function's return type defaults to \"int\" (C), or about inconsistent return types (C++)"),
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wselector",
    N_("Warn if a selector has multiple methods"),
    N_OPTS, 9, CL_ObjC | CL_ObjCXX, &warn_selector, 0, 0 },
  { "-Wsequence-point",
    N_("Warn about possible violations of sequence point rules"),
    N_OPTS, 15, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_sequence_point, 0, 0 },
  { "-Wshadow",
    N_("Warn when one local variable shadows another"),
    N_OPTS, 7, CL_COMMON, &warn_shadow, 0, 0 },
  { "-Wsign-compare",
    N_("Warn about signed-unsigned comparisons"),
    N_OPTS, 13, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, &warn_sign_compare, 0, 0 },
  { "-Wsign-promo",
    N_("Warn when overload promotes from unsigned to signed"),
    N_OPTS, 11, CL_CXX | CL_ObjCXX, &warn_sign_promo, 0, 0 },
  { "-Wstrict-aliasing",
    N_("Warn about code which might break strict aliasing rules"),
    N_OPTS, 16, CL_COMMON, 0, 0, 0 },
  { "-Wstrict-aliasing=",
    N_("Warn about code which might break strict aliasing rules"),
    N_OPTS, 17, CL_COMMON | CL_JOINED | CL_UINTEGER, 0, 0, 0 },
  { "-Wstrict-null-sentinel",
    N_("Warn about uncasted NULL used as sentinel"),
    N_OPTS, 21, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-Wstrict-prototypes",
    N_("Warn about unprototyped function declarations"),
    N_OPTS, 18, CL_C | CL_ObjC, &warn_strict_prototypes, 0, 0 },
  { "-Wswitch",
    N_("Warn about enumerated switches, with no default, missing a case"),
    N_OPTS, 7, CL_COMMON, &warn_switch, 0, 0 },
  { "-Wswitch-default",
    N_("Warn about enumerated switches missing a \"default:\" statement"),
    N_OPTS, 15, CL_COMMON, &warn_switch_default, 0, 0 },
  { "-Wswitch-enum",
    N_("Warn about all enumerated switches missing a specific case"),
    N_OPTS, 12, CL_COMMON, &warn_switch_enum, 0, 0 },
  { "-Wsynth",
    N_("Warn when synthesis behavior differs from Cfront"),
    N_OPTS, 6, CL_CXX | CL_ObjCXX, &warn_synth, 0, 0 },
  { "-Wsystem-headers",
    N_("Do not suppress warnings from system headers"),
    N_OPTS, 15, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_COMMON, &warn_system_headers, 0, 0 },
  { "-Wtraditional",
    N_("Warn about features not present in traditional C"),
    N_OPTS, 12, CL_C | CL_ObjC, &warn_traditional, 0, 0 },
  { "-Wtrigraphs",
    N_("Warn if trigraphs are encountered that might affect the meaning of the program"),
    N_OPTS, 10, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wundeclared-selector",
    N_("Warn about @selector()s without previously declared methods"),
    N_OPTS, 20, CL_ObjC | CL_ObjCXX, &warn_undeclared_selector, 0, 0 },
  { "-Wundef",
    N_("Warn if an undefined macro is used in an #if directive"),
    N_OPTS, 6, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wuninitialized",
    N_("Warn about uninitialized automatic variables"),
    N_OPTS, 14, CL_COMMON, &warn_uninitialized, 0, 0 },
  { "-Wunknown-pragmas",
    N_("Warn about unrecognized pragmas"),
    N_OPTS, 16, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wunreachable-code",
    N_("Warn about code that will never be executed"),
    N_OPTS, 17, CL_COMMON, &warn_notreached, 0, 0 },
  { "-Wunused",
    N_("Enable all -Wunused- warnings"),
    N_OPTS, 7, CL_COMMON, 0, 0, 0 },
  { "-Wunused-function",
    N_("Warn when a function is unused"),
    N_OPTS, 16, CL_COMMON, &warn_unused_function, 0, 0 },
  { "-Wunused-label",
    N_("Warn when a label is unused"),
    N_OPTS, 13, CL_COMMON, &warn_unused_label, 0, 0 },
  { "-Wunused-macros",
    N_("Warn about macros defined in the main file that are not used"),
    N_OPTS, 14, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wunused-parameter",
    N_("Warn when a function parameter is unused"),
    N_OPTS, 17, CL_COMMON, &warn_unused_parameter, 0, 0 },
  { "-Wunused-value",
    N_("Warn when an expression value is unused"),
    N_OPTS, 13, CL_COMMON, &warn_unused_value, 0, 0 },
  { "-Wunused-variable",
    N_("Warn when a variable is unused"),
    N_OPTS, 16, CL_COMMON, &warn_unused_variable, 0, 0 },
  { "-Wvariadic-macros",
    N_("Do not warn about using variadic macros when -pedantic"),
    N_OPTS, 16, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-Wwrite-strings",
    N_("Give strings the type \"array of char\""),
    N_OPTS, 14, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-ansi",
    N_("A synonym for -std=c89 (for C) or -std=c++98 (for C++)."),
    N_OPTS, 4, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-aux-info",
    N_("-aux-info <file>	Emit declaration information into <file>"),
    N_OPTS, 8, CL_COMMON | CL_SEPARATE, 0, 0, 0 },
  { "-aux-info=",
    0,
    N_OPTS, 9, CL_COMMON | CL_JOINED, 0, 0, 0 },
  { "-auxbase",
    0,
    N_OPTS, 7, CL_COMMON | CL_SEPARATE, 0, 0, 0 },
  { "-auxbase-strip",
    0,
    N_OPTS, 13, CL_COMMON | CL_SEPARATE, 0, 0, 0 },
  { "-d",
    N_("-d<letters>	Enable dumps from specific passes of the compiler"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_COMMON | CL_JOINED, 0, 0, 0 },
  { "-dumpbase",
    N_("-dumpbase <file>	Set the file basename to be used for dumps"),
    OPT_d, 8, CL_COMMON | CL_SEPARATE, 0, 0, 0 },
  { "-fPIC",
    N_("Generate position-independent code if possible (large mode)"),
    N_OPTS, 4, CL_COMMON | CL_REPORT, &flag_pic, 1, 2 },
  { "-fPIE",
    N_("Generate position-independent code for executables if possible (large mode)"),
    N_OPTS, 4, CL_COMMON | CL_REPORT, &flag_pie, 1, 2 },
  { "-fabi-version=",
    0,
    N_OPTS, 13, CL_COMMON | CL_JOINED | CL_UINTEGER, &flag_abi_version, 0, 0 },
  { "-faccess-control",
    N_("Enforce class member access control semantics"),
    N_OPTS, 15, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-falign-functions",
    N_("Align the start of functions"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &align_functions, 1, 0 },
  { "-falign-functions=",
    0,
    N_OPTS, 17, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-falign-jumps",
    N_("Align labels which are only reached by jumping"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &align_jumps, 1, 0 },
  { "-falign-jumps=",
    0,
    N_OPTS, 13, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-falign-labels",
    N_("Align all labels"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &align_labels, 1, 0 },
  { "-falign-labels=",
    0,
    N_OPTS, 14, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-falign-loops",
    N_("Align the start of loops"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &align_loops, 0, 0 },
  { "-falign-loops=",
    0,
    N_OPTS, 13, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-fall-virtual",
    0,
    N_OPTS, 12, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-falt-external-templates",
    N_("Change when template instances are emitted"),
    N_OPTS, 23, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fargument-alias",
    N_("Specify that arguments may alias each other and globals"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_argument_noalias, 1, 0 },
  { "-fargument-noalias",
    N_("Assume arguments may alias globals but not each other"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_argument_noalias, 1, 1 },
  { "-fargument-noalias-global",
    N_("Assume arguments alias neither each other nor globals"),
    N_OPTS, 24, CL_COMMON | CL_REPORT, &flag_argument_noalias, 1, 2 },
  { "-fasm",
    N_("Recognize the \"asm\" keyword"),
    N_OPTS, 4, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fasynchronous-unwind-tables",
    N_("Generate unwind tables that are exact at each instruction boundary"),
    N_OPTS, 27, CL_COMMON | CL_REPORT, &flag_asynchronous_unwind_tables, 0, 0 },
  { "-fbounds-check",
    N_("Generate code to check bounds before indexing arrays"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_bounds_check, 0, 0 },
  { "-fbranch-count-reg",
    N_("Replace add, compare, branch with branch on count register"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_branch_on_count_reg, 0, 0 },
  { "-fbranch-probabilities",
    N_("Use profiling information for branch probabilities"),
    N_OPTS, 21, CL_COMMON | CL_REPORT, &flag_branch_probabilities, 0, 0 },
  { "-fbranch-target-load-optimize",
    N_("Perform branch target load optimization before prologue / epilogue threading"),
    N_OPTS, 28, CL_COMMON | CL_REPORT, &flag_branch_target_load_optimize, 0, 0 },
  { "-fbranch-target-load-optimize2",
    N_("Perform branch target load optimization after prologue / epilogue threading"),
    N_OPTS, 29, CL_COMMON | CL_REPORT, &flag_branch_target_load_optimize2, 0, 0 },
  { "-fbtr-bb-exclusive",
    N_("Restrict target load migration not to re-use registers in any basic block"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_btr_bb_exclusive, 0, 0 },
  { "-fbuiltin",
    N_("Recognize built-in functions"),
    N_OPTS, 8, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fbuiltin-",
    0,
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED, 0, 0, 0 },
  { "-fcall-saved-",
    N_("-fcall-saved-<register>	Mark <register> as being preserved across functions"),
    N_OPTS, 12, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fcall-used-",
    N_("-fcall-used-<register>	Mark <register> as being corrupted by function calls"),
    N_OPTS, 11, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fcaller-saves",
    N_("Save registers around function calls"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_caller_saves, 0, 0 },
  { "-fcheck-new",
    N_("Check the return value of new"),
    N_OPTS, 10, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fcommon",
    N_("Do not put uninitialized globals in the common section"),
    N_OPTS, 7, CL_COMMON | CL_REPORT, &flag_no_common, 1, 0 },
  { "-fcond-mismatch",
    N_("Allow the arguments of the '?' operator to have different types"),
    N_OPTS, 14, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fconserve-space",
    N_("Reduce the size of object files"),
    N_OPTS, 15, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fconst-strings",
    N_("Make string literals \"const char[]\" not \"char[]\""),
    N_OPTS, 14, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fconstant-string-class=",
    N_("-fconst-string-class=<name>	Use class <name> for constant strings"),
    N_OPTS, 23, CL_ObjC | CL_ObjCXX | CL_JOINED, 0, 0, 0 },
  { "-fcprop-registers",
    N_("Perform a register copy-propagation optimization pass"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_cprop_registers, 0, 0 },
  { "-fcrossjumping",
    N_("Perform cross-jumping optimization"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_crossjumping, 0, 0 },
  { "-fcse-follow-jumps",
    N_("When running CSE, follow jumps to their targets"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_cse_follow_jumps, 0, 0 },
  { "-fcse-skip-blocks",
    N_("When running CSE, follow conditional jumps"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_cse_skip_blocks, 0, 0 },
  { "-fcx-limited-range",
    N_("Omit range reduction step when performing complex division"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_cx_limited_range, 0, 0 },
  { "-fdata-sections",
    N_("Place data items into their own section"),
    N_OPTS, 14, CL_COMMON | CL_REPORT, &flag_data_sections, 0, 0 },
  { "-fdefault-inline",
    N_("Inline member functions by default"),
    N_OPTS, 15, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fdefer-pop",
    N_("Defer popping functions args from stack until later"),
    N_OPTS, 10, CL_COMMON | CL_REPORT, &flag_defer_pop, 0, 0 },
  { "-fdelayed-branch",
    N_("Attempt to fill delay slots of branch instructions"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_delayed_branch, 0, 0 },
  { "-fdelete-null-pointer-checks",
    N_("Delete useless null pointer checks"),
    N_OPTS, 27, CL_COMMON | CL_REPORT, &flag_delete_null_pointer_checks, 0, 0 },
  { "-fdiagnostics-show-location=",
    N_("-fdiagnostics-show-location=[once|every-line]	How often to emit source location at the beginning of line-wrapped diagnostics"),
    N_OPTS, 27, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fdollars-in-identifiers",
    N_("Permit '$' as an identifier character"),
    N_OPTS, 23, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fdump-",
    N_("-fdump-<type>	Dump various compiler internals to a file"),
    N_OPTS, 6, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fdump-unnumbered",
    N_("Suppress output of instruction numbers and line number notes in debugging dumps"),
    OPT_fdump_, 16, CL_COMMON | CL_REPORT, &flag_dump_unnumbered, 0, 0 },
  { "-felide-constructors",
    0,
    N_OPTS, 19, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-feliminate-dwarf2-dups",
    N_("Perform DWARF2 duplicate elimination"),
    N_OPTS, 22, CL_COMMON | CL_REPORT, &flag_eliminate_dwarf2_dups, 0, 0 },
  { "-feliminate-unused-debug-symbols",
    N_("Perform unused type elimination in debug info"),
    N_OPTS, 31, CL_COMMON | CL_REPORT, &flag_debug_only_used_symbols, 0, 0 },
  { "-feliminate-unused-debug-types",
    N_("Perform unused type elimination in debug info"),
    N_OPTS, 29, CL_COMMON | CL_REPORT, &flag_eliminate_unused_debug_types, 0, 0 },
  { "-fenforce-eh-specs",
    N_("Generate code to check exception specifications"),
    N_OPTS, 17, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fenum-int-equiv",
    0,
    N_OPTS, 15, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fexceptions",
    N_("Enable exception handling"),
    N_OPTS, 11, CL_COMMON | CL_REPORT, &flag_exceptions, 0, 0 },
  { "-fexec-charset=",
    N_("-fexec-charset=<cset>	Convert all strings and character constants to character set <cset>"),
    N_OPTS, 14, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fexpensive-optimizations",
    N_("Perform a number of minor, expensive optimizations"),
    N_OPTS, 24, CL_COMMON | CL_REPORT, &flag_expensive_optimizations, 0, 0 },
  { "-fexternal-templates",
    0,
    N_OPTS, 19, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-ffast-math",
    0,
    N_OPTS, 10, CL_COMMON, 0, 0, 0 },
  { "-ffinite-math-only",
    N_("Assume no NaNs or infinities are generated"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_finite_math_only, 0, 0 },
  { "-ffixed-",
    N_("-ffixed-<register>	Mark <register> as being unavailable to the compiler"),
    N_OPTS, 7, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-ffixed-form",
    0,
    OPT_ffixed_, 11, CL_C | CL_ObjC, 0, 0, 0 },
  { "-ffixed-line-length-",
    0,
    OPT_ffixed_, 19, CL_C | CL_ObjC | CL_JOINED, 0, 0, 0 },
  { "-ffloat-store",
    N_("Don't allocate floats and doubles in extended-precision registers"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &flag_float_store, 0, 0 },
  { "-ffor-scope",
    N_("Scope of for-init-statement variables is local to the loop"),
    N_OPTS, 10, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fforce-addr",
    N_("Copy memory address constants into registers before use"),
    N_OPTS, 11, CL_COMMON | CL_REPORT, &flag_force_addr, 0, 0 },
  { "-fforce-mem",
    N_("Copy memory operands into registers before use"),
    N_OPTS, 10, CL_COMMON | CL_REPORT, &flag_force_mem, 0, 0 },
  { "-ffreestanding",
    N_("Do not assume that standard C libraries and \"main\" exist"),
    N_OPTS, 13, CL_C | CL_ObjC, 0, 0, 0 },
  { "-ffunction-cse",
    N_("Allow function addresses to be held in registers"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_no_function_cse, 1, 0 },
  { "-ffunction-sections",
    N_("Place each function into its own section"),
    N_OPTS, 18, CL_COMMON | CL_REPORT, &flag_function_sections, 0, 0 },
  { "-fgcse",
    N_("Perform global common subexpression elimination"),
    N_OPTS, 5, CL_COMMON | CL_REPORT, &flag_gcse, 0, 0 },
  { "-fgcse-after-reload",
    N_("Perform global common subexpression elimination after register allocation"),
    N_OPTS, 18, CL_COMMON | CL_REPORT, &flag_gcse_after_reload, 0, 0 },
  { "-fgcse-las",
    N_("Perform redundant load after store elimination in global common subexpression"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_gcse_las, 0, 0 },
  { "-fgcse-lm",
    N_("Perform enhanced load motion during global common subexpression elimination"),
    N_OPTS, 8, CL_COMMON | CL_REPORT, &flag_gcse_lm, 0, 0 },
  { "-fgcse-sm",
    N_("Perform store motion after global common subexpression elimination"),
    N_OPTS, 8, CL_COMMON | CL_REPORT, &flag_gcse_sm, 0, 0 },
  { "-fgnu-keywords",
    N_("Recognize GNU-defined keywords"),
    N_OPTS, 13, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fgnu-runtime",
    N_("Generate code for GNU runtime environment"),
    N_OPTS, 12, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fguess-branch-probability",
    N_("Enable guessing of branch probabilities"),
    N_OPTS, 25, CL_COMMON | CL_REPORT, &flag_guess_branch_prob, 0, 0 },
  { "-fguiding-decls",
    0,
    N_OPTS, 14, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fhandle-exceptions",
    0,
    N_OPTS, 18, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fhonor-std",
    0,
    N_OPTS, 10, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fhosted",
    N_("Assume normal C execution environment"),
    N_OPTS, 7, CL_C | CL_ObjC, 0, 0, 0 },
  { "-fhuge-objects",
    N_("Enable support for huge objects"),
    N_OPTS, 13, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fident",
    N_("Process #ident directives"),
    N_OPTS, 6, CL_COMMON | CL_REPORT, &flag_no_ident, 1, 0 },
  { "-fif-conversion",
    N_("Perform conversion of conditional jumps to branchless equivalents"),
    N_OPTS, 14, CL_COMMON | CL_REPORT, &flag_if_conversion, 0, 0 },
  { "-fif-conversion2",
    N_("Perform conversion of conditional jumps to conditional execution"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_if_conversion2, 0, 0 },
  { "-fimplement-inlines",
    N_("Export functions even if they can be inlined"),
    N_OPTS, 18, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fimplicit-inline-templates",
    N_("Emit implicit instantiations of inline templates"),
    N_OPTS, 26, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fimplicit-templates",
    N_("Emit implicit instantiations of templates"),
    N_OPTS, 19, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-finhibit-size-directive",
    N_("Do not generate .size directives"),
    N_OPTS, 23, CL_COMMON | CL_REPORT, &flag_inhibit_size_directive, 0, 0 },
  { "-finline",
    N_("Pay attention to the \"inline\" keyword"),
    N_OPTS, 7, CL_COMMON | CL_REPORT, &flag_no_inline, 1, 0 },
  { "-finline-functions",
    N_("Integrate simple functions into their callers"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_inline_functions, 0, 0 },
  { "-finline-functions-called-once",
    N_("Integrate functions called once into their callers"),
    N_OPTS, 29, CL_COMMON | CL_REPORT, &flag_inline_functions_called_once, 0, 0 },
  { "-finline-limit-",
    0,
    N_OPTS, 14, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-finline-limit=",
    N_("-finline-limit=<number>	Limit the size of inlined functions to <number>"),
    N_OPTS, 14, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-finput-charset=",
    N_("-finput-charset=<cset>	Specify the default character set for source files."),
    N_OPTS, 15, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-finstrument-functions",
    N_("Instrument function entry and exit with profiling calls"),
    N_OPTS, 21, CL_COMMON | CL_REPORT, &flag_instrument_function_entry_exit, 0, 0 },
  { "-fivopts",
    N_("Optimize induction variables on trees"),
    N_OPTS, 7, CL_COMMON | CL_REPORT, &flag_ivopts, 0, 0 },
  { "-fkeep-inline-functions",
    N_("Generate code for functions even if they are fully inlined"),
    N_OPTS, 22, CL_COMMON | CL_REPORT, &flag_keep_inline_functions, 0, 0 },
  { "-fkeep-static-consts",
    N_("Emit static const variables even if they are not used"),
    N_OPTS, 19, CL_COMMON | CL_REPORT, &flag_keep_static_consts, 0, 0 },
  { "-flabels-ok",
    0,
    N_OPTS, 10, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fleading-underscore",
    N_("Give external symbols a leading underscore"),
    N_OPTS, 19, CL_COMMON | CL_REPORT, &flag_leading_underscore, 0, 0 },
  { "-floop-optimize",
    N_("Perform loop optimizations"),
    N_OPTS, 14, CL_COMMON | CL_REPORT, &flag_loop_optimize, 0, 0 },
  { "-floop-optimize2",
    N_("Perform loop optimizations using the new loop optimizer"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_loop_optimize2, 0, 0 },
  { "-fmath-errno",
    N_("Set errno after built-in math functions"),
    N_OPTS, 11, CL_COMMON | CL_REPORT, &flag_errno_math, 0, 0 },
  { "-fmem-report",
    N_("Report on permanent memory allocation"),
    N_OPTS, 11, CL_COMMON | CL_REPORT, &mem_report, 0, 0 },
  { "-fmerge-all-constants",
    N_("Attempt to merge identical constants and constant variables"),
    N_OPTS, 20, CL_COMMON | CL_REPORT, &flag_merge_constants, 1, 2 },
  { "-fmerge-constants",
    N_("Attempt to merge identical constants across compilation units"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_merge_constants, 1, 1 },
  { "-fmessage-length=",
    N_("-fmessage-length=<number>	Limit diagnostics to <number> characters per line.  0 suppresses line-wrapping"),
    N_OPTS, 16, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-fmodulo-sched",
    N_("Perform SMS based modulo scheduling before the first scheduling pass"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_modulo_sched, 0, 0 },
  { "-fmove-loop-invariants",
    N_("Move loop invariant computations out of loops"),
    N_OPTS, 21, CL_COMMON | CL_REPORT, &flag_move_loop_invariants, 0, 0 },
  { "-fms-extensions",
    N_("Don't warn about uses of Microsoft extensions"),
    N_OPTS, 14, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fmudflap",
    N_("Add mudflap bounds-checking instrumentation for single-threaded program."),
    N_OPTS, 8, CL_COMMON | CL_REJECT_NEGATIVE | CL_REPORT, &flag_mudflap, 0, 0 },
  { "-fmudflapir",
    N_("Ignore read operations when inserting mudflap instrumentation."),
    N_OPTS, 10, CL_COMMON | CL_REJECT_NEGATIVE | CL_REPORT, &flag_mudflap_ignore_reads, 0, 0 },
  { "-fmudflapth",
    N_("Add mudflap bounds-checking instrumentation for multi-threaded program."),
    N_OPTS, 10, CL_COMMON | CL_REJECT_NEGATIVE | CL_REPORT, &flag_mudflap_threads, 0, 0 },
  { "-fname-mangling-version-",
    0,
    N_OPTS, 23, CL_CXX | CL_ObjCXX | CL_JOINED, 0, 0, 0 },
  { "-fnew-abi",
    0,
    N_OPTS, 8, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fnext-runtime",
    N_("Generate code for NeXT (Apple Mac OS X) runtime environment"),
    N_OPTS, 13, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fnil-receivers",
    N_("Assume that receivers of Objective-C messages may be nil"),
    N_OPTS, 14, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fnon-call-exceptions",
    N_("Support synchronous non-call exceptions"),
    N_OPTS, 20, CL_COMMON | CL_REPORT, &flag_non_call_exceptions, 0, 0 },
  { "-fnonansi-builtins",
    0,
    N_OPTS, 17, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fnonnull-objects",
    0,
    N_OPTS, 16, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fobjc-exceptions",
    N_("Enable Objective-C exception and synchronization syntax"),
    N_OPTS, 16, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fobjc-sjlj-exceptions",
    N_("Enable Objective-C setjmp exception handling runtime"),
    N_OPTS, 21, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fomit-frame-pointer",
    N_("When possible do not generate stack frames"),
    N_OPTS, 19, CL_COMMON | CL_REPORT, &flag_omit_frame_pointer, 0, 0 },
  { "-foperator-names",
    N_("Recognize C++ kewords like \"compl\" and \"xor\""),
    N_OPTS, 15, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-foptimize-register-move",
    N_("Do the full register move optimization pass"),
    N_OPTS, 23, CL_COMMON | CL_REPORT, &flag_regmove, 0, 0 },
  { "-foptimize-sibling-calls",
    N_("Optimize sibling and tail recursive calls"),
    N_OPTS, 23, CL_COMMON | CL_REPORT, &flag_optimize_sibling_calls, 0, 0 },
  { "-foptional-diags",
    N_("Enable optional diagnostics"),
    N_OPTS, 15, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fpack-struct",
    N_("Pack structure members together without holes"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &flag_pack_struct, 0, 0 },
  { "-fpack-struct=",
    N_("-fpack-struct=<number>	Set initial maximum structure member alignment"),
    N_OPTS, 13, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-fpcc-struct-return",
    N_("Return small aggregates in memory, not registers"),
    N_OPTS, 18, CL_COMMON | CL_REPORT, &flag_pcc_struct_return, 1, 1 },
  { "-fpch-deps",
    0,
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fpch-preprocess",
    N_("Look for and use PCH files even when preprocessing"),
    N_OPTS, 15, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fpeel-loops",
    N_("Perform loop peeling"),
    N_OPTS, 11, CL_COMMON | CL_REPORT, &flag_peel_loops, 0, 0 },
  { "-fpeephole",
    N_("Enable machine specific peephole optimizations"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_no_peephole, 1, 0 },
  { "-fpeephole2",
    N_("Enable an RTL peephole pass before sched2"),
    N_OPTS, 10, CL_COMMON | CL_REPORT, &flag_peephole2, 0, 0 },
  { "-fpermissive",
    N_("Downgrade conformance errors to warnings"),
    N_OPTS, 11, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fpic",
    N_("Generate position-independent code if possible (small mode)"),
    N_OPTS, 4, CL_COMMON | CL_REPORT, &flag_pic, 1, 1 },
  { "-fpie",
    N_("Generate position-independent code for executables if possible (small mode)"),
    N_OPTS, 4, CL_COMMON | CL_REPORT, &flag_pie, 1, 1 },
  { "-fprefetch-loop-arrays",
    N_("Generate prefetch instructions, if available, for arrays in loops"),
    N_OPTS, 21, CL_COMMON | CL_REPORT, &flag_prefetch_loop_arrays, 0, 0 },
  { "-fpreprocessed",
    N_("Treat the input file as already preprocessed"),
    N_OPTS, 13, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fprofile",
    N_("Enable basic program profiling code"),
    N_OPTS, 8, CL_COMMON | CL_REPORT, &profile_flag, 0, 0 },
  { "-fprofile-arcs",
    N_("Insert arc-based program profiling code"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &profile_arc_flag, 0, 0 },
  { "-fprofile-generate",
    N_("Enable common options for generating profile info for profile feedback directed optimizations"),
    N_OPTS, 17, CL_COMMON, 0, 0, 0 },
  { "-fprofile-use",
    N_("Enable common options for performing profile feedback directed optimizations"),
    N_OPTS, 12, CL_COMMON, 0, 0, 0 },
  { "-fprofile-values",
    N_("Insert code to profile values of expressions"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_profile_values, 0, 0 },
  { "-frandom-seed",
    0,
    N_OPTS, 12, CL_COMMON, 0, 0, 0 },
  { "-frandom-seed=",
    N_("-frandom-seed=<string>	Make compile reproducible using <string>"),
    N_OPTS, 13, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-freg-struct-return",
    N_("Return small aggregates in registers"),
    N_OPTS, 18, CL_COMMON | CL_REPORT, &flag_pcc_struct_return, 1, 0 },
  { "-fregmove",
    N_("Enables a register move optimization"),
    N_OPTS, 8, CL_COMMON | CL_REPORT, &flag_regmove, 0, 0 },
  { "-frename-registers",
    N_("Perform a register renaming optimization pass"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_rename_registers, 0, 0 },
  { "-freorder-blocks",
    N_("Reorder basic blocks to improve code placement"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_reorder_blocks, 0, 0 },
  { "-freorder-blocks-and-partition",
    N_("Reorder basic blocks and partition into hot and cold sections"),
    N_OPTS, 29, CL_COMMON | CL_REPORT, &flag_reorder_blocks_and_partition, 0, 0 },
  { "-freorder-functions",
    N_("Reorder functions to improve code placement"),
    N_OPTS, 18, CL_COMMON | CL_REPORT, &flag_reorder_functions, 0, 0 },
  { "-freplace-objc-classes",
    N_("Used in Fix-and-Continue mode to indicate that object files may be swapped in at runtime"),
    N_OPTS, 21, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-frepo",
    N_("Enable automatic template instantiation"),
    N_OPTS, 5, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-frerun-cse-after-loop",
    N_("Add a common subexpression elimination pass after loop optimizations"),
    N_OPTS, 21, CL_COMMON | CL_REPORT, &flag_rerun_cse_after_loop, 0, 0 },
  { "-frerun-loop-opt",
    N_("Run the loop optimizer twice"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_rerun_loop_opt, 0, 0 },
  { "-freschedule-modulo-scheduled-loops",
    N_("Enable/Disable the traditional scheduling in loops that already passed modulo scheduling"),
    N_OPTS, 34, CL_COMMON | CL_REPORT, &flag_resched_modulo_sched, 0, 0 },
  { "-frounding-math",
    N_("Disable optimizations that assume default FP rounding behavior"),
    N_OPTS, 14, CL_COMMON | CL_REPORT, &flag_rounding_math, 0, 0 },
  { "-frtti",
    N_("Generate run time type descriptor information"),
    N_OPTS, 5, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fsched-interblock",
    N_("Enable scheduling across basic blocks"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_schedule_interblock, 0, 0 },
  { "-fsched-spec",
    N_("Allow speculative motion of non-loads"),
    N_OPTS, 11, CL_COMMON | CL_REPORT, &flag_schedule_speculative, 0, 0 },
  { "-fsched-spec-load",
    N_("Allow speculative motion of some loads"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_schedule_speculative_load, 0, 0 },
  { "-fsched-spec-load-dangerous",
    N_("Allow speculative motion of more loads"),
    N_OPTS, 26, CL_COMMON | CL_REPORT, &flag_schedule_speculative_load_dangerous, 0, 0 },
  { "-fsched-stalled-insns",
    N_("Allow premature scheduling of queued insns"),
    N_OPTS, 20, CL_COMMON | CL_REPORT, &flag_sched_stalled_insns, 0, 0 },
  { "-fsched-stalled-insns-dep",
    N_("Set dependence distance checking in premature scheduling of queued insns"),
    N_OPTS, 24, CL_COMMON | CL_REPORT, &flag_sched_stalled_insns_dep, 1, 1 },
  { "-fsched-stalled-insns-dep=",
    N_("-fsched-stalled-insns-dep=<number>	Set dependence distance checking in premature scheduling of queued insns"),
    N_OPTS, 25, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-fsched-stalled-insns=",
    N_("-fsched-stalled-insns=<number>	Set number of queued insns that can be prematurely scheduled"),
    N_OPTS, 21, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-fsched-verbose=",
    N_("-fsched-verbose=<number>	Set the verbosity level of the scheduler"),
    N_OPTS, 15, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fsched2-use-superblocks",
    N_("If scheduling post reload, do superblock scheduling"),
    N_OPTS, 23, CL_COMMON | CL_REPORT, &flag_sched2_use_superblocks, 0, 0 },
  { "-fsched2-use-traces",
    N_("If scheduling post reload, do trace scheduling"),
    N_OPTS, 18, CL_COMMON | CL_REPORT, &flag_sched2_use_traces, 0, 0 },
  { "-fschedule-insns",
    N_("Reschedule instructions before register allocation"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_schedule_insns, 0, 0 },
  { "-fschedule-insns2",
    N_("Reschedule instructions after register allocation"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_schedule_insns_after_reload, 0, 0 },
  { "-fshared-data",
    N_("Mark data as shared rather than private"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &flag_shared_data, 0, 0 },
  { "-fshort-double",
    N_("Use the same size for double as for float"),
    N_OPTS, 13, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fshort-enums",
    N_("Use the narrowest integer type possible for enumeration types"),
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fshort-wchar",
    N_("Force the underlying type for \"wchar_t\" to be \"unsigned short\""),
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fshow-column",
    0,
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fsignaling-nans",
    N_("Disable optimizations observable by IEEE signaling NaNs"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_signaling_nans, 0, 0 },
  { "-fsigned-bitfields",
    N_("When \"signed\" or \"unsigned\" is not given make the bitfield signed"),
    N_OPTS, 17, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fsigned-char",
    N_("Make \"char\" signed by default"),
    N_OPTS, 12, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fsingle-precision-constant",
    N_("Convert floating point constants to single precision constants"),
    N_OPTS, 26, CL_COMMON | CL_REPORT, &flag_single_precision_constant, 0, 0 },
  { "-fspeculative-prefetching",
    N_("Use value profiling for speculative prefetching"),
    N_OPTS, 24, CL_COMMON | CL_REPORT, &flag_speculative_prefetching, 0, 0 },
  { "-fsplit-ivs-in-unroller",
    N_("Split lifetimes of induction variables when loops are unrolled."),
    N_OPTS, 22, CL_COMMON | CL_REPORT, &flag_split_ivs_in_unroller, 0, 0 },
  { "-fsquangle",
    0,
    N_OPTS, 9, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fstack-check",
    N_("Insert stack checking code into the program"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &flag_stack_check, 0, 0 },
  { "-fstack-limit",
    0,
    N_OPTS, 12, CL_COMMON, 0, 0, 0 },
  { "-fstack-limit-register=",
    N_("-fstack-limit-register=<register>	Trap if the stack goes past <register>"),
    N_OPTS, 22, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fstack-limit-symbol=",
    N_("-fstack-limit-symbol=<name>	Trap if the stack goes past symbol <name>"),
    N_OPTS, 20, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fstats",
    N_("Display statistics accumulated during compilation"),
    N_OPTS, 6, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fstrength-reduce",
    N_("Perform strength reduction optimizations"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_strength_reduce, 0, 0 },
  { "-fstrict-aliasing",
    N_("Assume strict aliasing rules apply"),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_strict_aliasing, 0, 0 },
  { "-fstrict-prototype",
    0,
    N_OPTS, 17, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fsyntax-only",
    N_("Check for syntax errors, then stop"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &flag_syntax_only, 0, 0 },
  { "-ftabstop=",
    N_("-ftabstop=<number>	Distance between tab stops for column reporting"),
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-ftemplate-depth-",
    N_("-ftemplate-depth-<number>	Specify maximum template instantiation depth"),
    N_OPTS, 16, CL_CXX | CL_ObjCXX | CL_JOINED | CL_REJECT_NEGATIVE | CL_UINTEGER, 0, 0, 0 },
  { "-ftest-coverage",
    N_("Create data files needed by \"gcov\""),
    N_OPTS, 14, CL_COMMON | CL_REPORT, &flag_test_coverage, 0, 0 },
  { "-fthis-is-variable",
    0,
    N_OPTS, 17, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fthread-jumps",
    N_("Perform jump threading optimizations"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_thread_jumps, 0, 0 },
  { "-fthreadsafe-statics",
    N_("-fno-threadsafe-statics	Do not generate thread-safe code for initializing local statics."),
    N_OPTS, 19, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-ftime-report",
    N_("Report the time taken by each compiler pass"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &time_report, 0, 0 },
  { "-ftls-model=",
    N_("-ftls-model=[global-dynamic|local-dynamic|initial-exec|local-exec]	Set the default thread-local storage code generation model"),
    N_OPTS, 11, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-ftracer",
    N_("Perform superblock formation via tail duplication"),
    N_OPTS, 7, CL_COMMON | CL_REPORT, &flag_tracer, 0, 0 },
  { "-ftrapping-math",
    N_("Assume floating-point operations can trap"),
    N_OPTS, 14, CL_COMMON | CL_REPORT, &flag_trapping_math, 0, 0 },
  { "-ftrapv",
    N_("Trap for signed overflow in addition, subtraction and multiplication"),
    N_OPTS, 6, CL_COMMON | CL_REPORT, &flag_trapv, 0, 0 },
  { "-ftree-based-profiling",
    N_("Use tree-ssa based implementation of profiling"),
    N_OPTS, 21, CL_COMMON | CL_REPORT, &flag_tree_based_profiling, 0, 0 },
  { "-ftree-ccp",
    N_("Enable SSA-CCP optimization on trees"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_ccp, 0, 0 },
  { "-ftree-ch",
    N_("Enable loop header copying on trees"),
    N_OPTS, 8, CL_COMMON | CL_REPORT, &flag_tree_ch, 0, 0 },
  { "-ftree-combine-temps",
    N_("Coalesce memory temporaries in the SSA->normal pass"),
    N_OPTS, 19, CL_COMMON | CL_REPORT, &flag_tree_combine_temps, 0, 0 },
  { "-ftree-copyrename",
    N_("Replace SSA temporaries with better names in copies."),
    N_OPTS, 16, CL_COMMON | CL_REPORT, &flag_tree_copyrename, 0, 0 },
  { "-ftree-dce",
    N_("Enable SSA dead code elimination optimization on trees"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_dce, 0, 0 },
  { "-ftree-dominator-opts",
    N_("Enable dominator optimizations"),
    N_OPTS, 20, CL_COMMON | CL_REPORT, &flag_tree_dom, 0, 0 },
  { "-ftree-dse",
    N_("Enable dead store elimination"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_dse, 0, 0 },
  { "-ftree-fre",
    N_("Enable Full Redundancy Elimination (FRE) on trees"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_fre, 0, 0 },
  { "-ftree-loop-im",
    N_("Enable loop invariant motion on trees"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_tree_loop_im, 0, 0 },
  { "-ftree-loop-ivcanon",
    N_("Create canonical induction variables in loops"),
    N_OPTS, 18, CL_COMMON | CL_REPORT, &flag_tree_loop_ivcanon, 0, 0 },
  { "-ftree-loop-linear",
    N_("Enable linear loop transforms on trees"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_tree_loop_linear, 0, 0 },
  { "-ftree-loop-optimize",
    N_("Enable loop optimizations on tree level"),
    N_OPTS, 19, CL_COMMON | CL_REPORT, &flag_tree_loop_optimize, 0, 0 },
  { "-ftree-lrs",
    N_("Perform live range splitting during the SSA->normal pass."),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_live_range_split, 0, 0 },
  { "-ftree-pre",
    N_("Enable SSA-PRE optimization on trees"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_pre, 0, 0 },
  { "-ftree-sra",
    N_("Perform scalar replacement of aggregates"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_sra, 0, 0 },
  { "-ftree-ter",
    N_("Replace temporary expressions in the SSA->normal pass"),
    N_OPTS, 9, CL_COMMON | CL_REPORT, &flag_tree_ter, 0, 0 },
  { "-ftree-vectorize",
    N_("Enable loop vectorization on trees"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_tree_vectorize, 0, 0 },
  { "-ftree-vectorizer-verbose=",
    N_("-ftree-vectorizer-verbose=<number>	Set the verbosity level of the vectorizer"),
    N_OPTS, 25, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-funit-at-a-time",
    N_("Compile whole compilation unit at a time"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_unit_at_a_time, 0, 0 },
  { "-funroll-all-loops",
    N_("Perform loop unrolling for all loops"),
    N_OPTS, 17, CL_COMMON | CL_REPORT, &flag_unroll_all_loops, 0, 0 },
  { "-funroll-loops",
    N_("Perform loop unrolling when iteration count is known"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_unroll_loops, 0, 0 },
  { "-funsafe-math-optimizations",
    N_("Allow math optimizations that may violate IEEE or ISO standards"),
    N_OPTS, 26, CL_COMMON | CL_REPORT, &flag_unsafe_math_optimizations, 0, 0 },
  { "-funsigned-bitfields",
    N_("When \"signed\" or \"unsigned\" is not given make the bitfield unsigned"),
    N_OPTS, 19, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-funsigned-char",
    N_("Make \"char\" unsigned by default"),
    N_OPTS, 14, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-funswitch-loops",
    N_("Perform loop unswitching"),
    N_OPTS, 15, CL_COMMON | CL_REPORT, &flag_unswitch_loops, 0, 0 },
  { "-funwind-tables",
    N_("Just generate unwind tables for exception handling"),
    N_OPTS, 14, CL_COMMON | CL_REPORT, &flag_unwind_tables, 0, 0 },
  { "-fuse-cxa-atexit",
    N_("Use __cxa_atexit to register destructors"),
    N_OPTS, 15, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fvar-tracking",
    N_("Perform variable tracking"),
    N_OPTS, 13, CL_COMMON | CL_REPORT, &flag_var_tracking, 0, 0 },
  { "-fvariable-expansion-in-unroller",
    N_("Apply variable expansion when loops are unrolled."),
    N_OPTS, 31, CL_COMMON | CL_REPORT, &flag_variable_expansion_in_unroller, 0, 0 },
  { "-fverbose-asm",
    N_("Add extra commentary to assembler output"),
    N_OPTS, 12, CL_COMMON | CL_REPORT, &flag_verbose_asm, 0, 0 },
  { "-fvisibility-inlines-hidden",
    N_("Marks all inlined methods as having hidden visibility"),
    N_OPTS, 26, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fvisibility=",
    N_("-fvisibility=[default|internal|hidden|protected]	Set the default symbol visibility"),
    N_OPTS, 12, CL_COMMON | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fvpt",
    N_("Use expression value profiles in optimizations"),
    N_OPTS, 4, CL_COMMON | CL_REPORT, &flag_value_profile_transformations, 0, 0 },
  { "-fvtable-gc",
    N_("Discard unused virtual functions"),
    N_OPTS, 10, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fvtable-thunks",
    N_("Implement vtables using thunks"),
    N_OPTS, 14, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fweak",
    N_("Emit common-like symbols as weak symbols"),
    N_OPTS, 5, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fweb",
    N_("Construct webs and split unrelated uses of single variable"),
    N_OPTS, 4, CL_COMMON | CL_REPORT, &flag_web, 0, 0 },
  { "-fwide-exec-charset=",
    N_("-fwide-exec-charset=<cset>	Convert all wide strings and character constants to character set <cset>"),
    N_OPTS, 19, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_REJECT_NEGATIVE, 0, 0, 0 },
  { "-fworking-directory",
    N_("Generate a #line directive pointing at the current working directory"),
    N_OPTS, 18, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-fwrapv",
    N_("Assume signed arithmetic overflow wraps around"),
    N_OPTS, 6, CL_COMMON | CL_REPORT, &flag_wrapv, 0, 0 },
  { "-fxref",
    N_("Emit cross referencing information"),
    N_OPTS, 5, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-fzero-initialized-in-bss",
    N_("Put zero initialized data in the bss section"),
    N_OPTS, 24, CL_COMMON | CL_REPORT, &flag_zero_initialized_in_bss, 0, 0 },
  { "-fzero-link",
    N_("Generate lazy class lookup (via objc_getClass()) for use in Zero-Link mode"),
    N_OPTS, 10, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-g",
    N_("Generate debug information in default format"),
    N_OPTS, 1, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gcoff",
    N_("Generate debug information in COFF format"),
    OPT_g, 5, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gdwarf-2",
    N_("Generate debug information in DWARF v2 format"),
    OPT_g, 8, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gen-decls",
    N_("Dump declarations to a .decl file"),
    OPT_g, 9, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-ggdb",
    N_("Generate debug information in default extended format"),
    OPT_g, 4, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gstabs",
    N_("Generate debug information in STABS format"),
    OPT_g, 6, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gstabs+",
    N_("Generate debug information in extended STABS format"),
    OPT_gstabs, 7, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gvms",
    N_("Generate debug information in VMS format"),
    OPT_g, 4, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gxcoff",
    N_("Generate debug information in XCOFF format"),
    OPT_g, 6, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-gxcoff+",
    N_("Generate debug information in extended XCOFF format"),
    OPT_gxcoff, 7, CL_COMMON | CL_JOINED | CL_MISSING_OK, 0, 0, 0 },
  { "-idirafter",
    N_("-idirafter <dir>	Add <dir> to the end of the system include path"),
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-imacros",
    N_("-imacros <file>	Accept definition of macros in <file>"),
    N_OPTS, 7, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-include",
    N_("-include <file>	Include the contents of <file> before other files"),
    N_OPTS, 7, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-iprefix",
    N_("-iprefix <path>	Specify <path> as a prefix for next two options"),
    N_OPTS, 7, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-iquote",
    N_("-iquote <dir>	Add <dir> to the end of the quote include path"),
    N_OPTS, 6, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-isysroot",
    N_("-isysroot <dir>	Set <dir> to be the system root directory"),
    N_OPTS, 8, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-isystem",
    N_("-isystem <dir>	Add <dir> to the start of the system include path"),
    N_OPTS, 7, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-iwithprefix",
    N_("-iwithprefix <dir>	Add <dir> to the end of the system include path"),
    N_OPTS, 11, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-iwithprefixbefore",
    N_("-iwithprefixbefore <dir>	Add <dir> to the end of the main include path"),
    OPT_iwithprefix, 17, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-lang-asm",
    0,
    N_OPTS, 8, CL_C | CL_UNDOCUMENTED, 0, 0, 0 },
  { "-lang-fortran",
    0,
    N_OPTS, 12, CL_C | CL_UNDOCUMENTED, 0, 0, 0 },
  { "-lang-objc",
    0,
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_UNDOCUMENTED, 0, 0, 0 },
  { "-m",
    0,
    N_OPTS, 1, CL_COMMON | CL_JOINED, 0, 0, 0 },
  { "-nostdinc",
    N_("Do not search standard system include directories (those specified with -isystem will still be used)"),
    N_OPTS, 8, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-nostdinc++",
    N_("Do not search standard system include directories for C++"),
    N_OPTS, 10, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-o",
    N_("-o <file>	Place output into <file>"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_COMMON | CL_JOINED | CL_SEPARATE, 0, 0, 0 },
  { "-p",
    N_("Enable function profiling"),
    N_OPTS, 1, CL_COMMON, &profile_flag, 0, 0 },
  { "-pedantic",
    N_("Issue warnings needed for strict compliance to the standard"),
    N_OPTS, 8, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_COMMON, &pedantic, 0, 0 },
  { "-pedantic-errors",
    N_("Like -pedantic but issue them as errors"),
    N_OPTS, 15, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_COMMON, 0, 0, 0 },
  { "-print-objc-runtime-info",
    N_("Generate C header of platform-specific features"),
    N_OPTS, 23, CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-quiet",
    N_("Do not display functions compiled or elapsed time"),
    N_OPTS, 5, CL_COMMON, &quiet_flag, 0, 0 },
  { "-remap",
    N_("Remap file names when including files"),
    N_OPTS, 5, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-std=c++98",
    N_("Conform to the ISO 1998 C++ standard"),
    N_OPTS, 9, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-std=c89",
    N_("Conform to the ISO 1990 C standard"),
    N_OPTS, 7, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=c99",
    N_("Conform to the ISO 1999 C standard"),
    N_OPTS, 7, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=c9x",
    N_("Deprecated in favor of -std=c99"),
    N_OPTS, 7, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=gnu++98",
    N_("Conform to the ISO 1998 C++ standard with GNU extensions"),
    N_OPTS, 11, CL_CXX | CL_ObjCXX, 0, 0, 0 },
  { "-std=gnu89",
    N_("Conform to the ISO 1990 C standard with GNU extensions"),
    N_OPTS, 9, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=gnu99",
    N_("Conform to the ISO 1999 C standard with GNU extensions"),
    N_OPTS, 9, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=gnu9x",
    N_("Deprecated in favor of -std=gnu99"),
    N_OPTS, 9, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=iso9899:1990",
    N_("Conform to the ISO 1990 C standard"),
    N_OPTS, 16, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=iso9899:199409",
    N_("Conform to the ISO 1990 C standard as amended in 1994"),
    N_OPTS, 18, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=iso9899:1999",
    N_("Conform to the ISO 1999 C standard"),
    N_OPTS, 16, CL_C | CL_ObjC, 0, 0, 0 },
  { "-std=iso9899:199x",
    N_("Deprecated in favor of -std=iso9899:1999"),
    N_OPTS, 16, CL_C | CL_ObjC, 0, 0, 0 },
  { "-traditional-cpp",
    N_("Enable traditional preprocessing"),
    N_OPTS, 15, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-trigraphs",
    N_("-trigraphs	Support ISO C trigraphs"),
    N_OPTS, 9, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-undef",
    N_("Do not predefine system-specific and GCC-specific macros"),
    N_OPTS, 5, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-v",
    N_("Enable verbose output"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX, 0, 0, 0 },
  { "-version",
    N_("Display the compiler's version"),
    N_OPTS, 7, CL_COMMON, &version_flag, 0, 0 },
  { "-w",
    N_("Suppress warnings"),
    N_OPTS, 1, CL_C | CL_CXX | CL_ObjC | CL_ObjCXX | CL_COMMON, &inhibit_warnings, 0, 0 }
};
