#
# Makefile for MIPS-specific library files..
#

lib-y	+= csum_partial_copy.o memcpy.o memcpy-inatomic.o promlib.o strlen_user.o strncpy_user.o \
	   strnlen_user.o uncached.o iomap.o

EXTRA_AFLAGS := $(CFLAGS)
