/* This file is part of GDB.

   Copyright 2002 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
 
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.

   --

   This file was generated by the program igen */

#ifndef ICACHE_H
#define ICACHE_H

typedef idecode_semantic * idecode_icache_0
(SIM_DESC sd,
 instruction_address cia,
 idecode_cache *cache_entry);

typedef idecode_semantic * idecode_icache_1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia,
 idecode_cache *cache_entry);

/* This generated file (icache.h) is intentionally left blank - generating jump engine */

#endif /* _ICACHE_H_*/
