/* This file is part of GDB.

   Copyright 2002 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
 
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.

   --

   This file was generated by the program igen */

#ifndef IRUN_C
#define IRUN_C

#include "sim-main.h"
#include "engine.h"
#include "idecode.h"
#include "bfd.h"

void
sim_engine_run (SIM_DESC sd,
                int next_cpu_nr,
                int nr_cpus,
                int siggnal)
{
  engine_run (sd, next_cpu_nr, nr_cpus, siggnal);
}

#endif /* _IRUN_C_*/
