/* This file is part of GDB.

   Copyright 2002 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
 
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.

   --

   This file was generated by the program igen */

#ifndef ITABLE_H
#define ITABLE_H

typedef enum {
#line 92 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_RSVD_SPECIAL,
#line 516 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ADD_SPECIAL,
#line 544 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ADDI_NORMAL,
#line 581 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ADDIU_NORMAL,
#line 610 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ADDU_SPECIAL,
#line 637 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_AND_SPECIAL,
#line 657 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ANDI_NORMAL,
#line 679 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BEQ_NORMAL,
#line 703 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BEQL_NORMAL,
#line 728 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BGEZ_REGIMM,
#line 752 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BGEZAL_REGIMM,
#line 779 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BGEZALL_REGIMM,
#line 809 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BGEZL_REGIMM,
#line 834 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BGTZ_NORMAL,
#line 858 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BGTZL_NORMAL,
#line 885 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BLEZ_NORMAL,
#line 911 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BLEZL_NORMAL,
#line 936 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BLTZ_REGIMM,
#line 960 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BLTZAL_REGIMM,
#line 989 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BLTZALL_REGIMM,
#line 1017 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BLTZL_REGIMM,
#line 1044 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BNE_NORMAL,
#line 1068 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BNEL_NORMAL,
#line 1093 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BREAK_SPECIAL,
#line 1441 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_DIV_SPECIAL,
#line 1482 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_DIVU_SPECIAL,
#line 1893 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_J_NORMAL,
#line 1915 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_JAL_NORMAL,
#line 1937 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_JALR_SPECIAL,
#line 1959 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_JR_SPECIAL,
#line 2088 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LB_NORMAL,
#line 2107 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LBU_NORMAL,
#line 2191 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LH_NORMAL,
#line 2210 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LHU_NORMAL,
#line 2229 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LL_NORMAL,
#line 2310 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LUI_NORMAL,
#line 2331 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LW_NORMAL,
#line 2350 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LWCz_NORMAL,
#line 2369 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LWL_NORMAL,
#line 2388 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LWR_NORMAL,
#line 2474 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MFHI_SPECIAL,
#line 2498 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MFLO_SPECIAL,
#line 2514 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MOVN_SPECIAL,
#line 2533 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MOVZ_SPECIAL,
#line 2596 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MTHI_SPECIAL,
#line 2613 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MTLO_SPECIAL,
#line 2666 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MULT_SPECIAL,
#line 2709 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MULTU_SPECIAL,
#line 2742 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_NOR_SPECIAL,
#line 2768 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_OR_SPECIAL,
#line 2795 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ORI_NORMAL,
#line 2814 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_PREF_NORMAL,
#line 2960 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SB_NORMAL,
#line 2979 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SC_NORMAL,
#line 3127 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SH_NORMAL,
#line 3154 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SLLa_SPECIAL,
#line 3197 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SLLV_SPECIAL,
#line 3223 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SLT_SPECIAL,
#line 3249 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SLTI_NORMAL,
#line 3275 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SLTIU_NORMAL,
#line 3302 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SLTU_SPECIAL,
#line 3331 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SRA_SPECIAL,
#line 3362 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SRAV_SPECIAL,
#line 3392 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SRL_SPECIAL,
#line 3422 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SRLV_SPECIAL,
#line 3441 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SUB_SPECIAL,
#line 3477 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SUBU_SPECIAL,
#line 3496 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SW_NORMAL,
#line 3515 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SWCz_NORMAL,
#line 3534 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SWL_NORMAL,
#line 3553 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SWR_NORMAL,
#line 3572 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SYNC_SPECIAL,
#line 3591 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SYSCALL_SPECIAL,
#line 3610 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TEQ_SPECIAL,
#line 3628 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TEQI_REGIMM,
#line 3646 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TGE_SPECIAL,
#line 3664 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TGEI_REGIMM,
#line 3682 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TGEIU_REGIMM,
#line 3700 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TGEU_SPECIAL,
#line 3718 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLT_SPECIAL,
#line 3736 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLTI_REGIMM,
#line 3754 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLTIU_REGIMM,
#line 3772 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLTU_SPECIAL,
#line 3790 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TNE_SPECIAL,
#line 3808 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TNEI_REGIMM,
#line 3833 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_XOR_SPECIAL,
#line 3859 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_XORI_NORMAL,
#line 4072 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ABS_fmt_COP1,
#line 4095 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ADD_fmt_COP1,
#line 4175 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BC1b_COP1S,
#line 4213 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_C_cond_fmtb_COP1,
#line 4252 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_CEIL_W_COP1,
#line 4287 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_CFC1b_COP1,
#line 4336 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_CTC1b_COP1,
#line 4369 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_CVT_D_fmt_COP1,
#line 4429 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_CVT_S_fmt_COP1,
#line 4477 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_CVT_W_fmt_COP1,
#line 4501 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_DIV_fmt_COP1,
#line 4619 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_FLOOR_W_fmt_COP1,
#line 4651 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LDC1b_COP1,
#line 4699 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_LWC1_COP1,
#line 4764 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MFC1b_COP1,
#line 4782 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MOV_fmt_COP1,
#line 4806 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MOVtf_SPECIAL,
#line 4824 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MOVtf_fmt_COP1,
#line 4855 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MOVN_fmt_COP1,
#line 4880 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MOVZ_fmt_COP1,
#line 4929 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MTC1b_COP1,
#line 4946 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MUL_fmt_COP1,
#line 4968 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_NEG_fmt_COP1,
#line 5096 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_RECIP_fmt_COP1,
#line 5128 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ROUND_W_fmt_COP1,
#line 5149 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_RSQRT_fmt_COP1,
#line 5174 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SDC1b_COP1,
#line 5223 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SQRT_fmt_COP1,
#line 5243 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SUB_fmt_COP1,
#line 5266 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SWC1_COP1,
#line 5312 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_SWXC1_COP1X,
#line 5371 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TRUNC_W_COP1,
#line 5399 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BC0F_COP0,
#line 5422 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BC0FL_COP0,
#line 5437 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BC0T_COP0,
#line 5451 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_BC0TL_COP0,
#line 5466 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_CACHE_NORMAL,
#line 5517 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_ERET_COP0,
#line 5544 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MFC0_COP0,
#line 5564 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_MTC0_COP0,
#line 5583 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_RFE_COP0,
#line 5598 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_COPz_NORMAL,
#line 5617 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLBP_COP0,
#line 5632 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLBR_COP0,
#line 5647 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLBWI_COP0,
#line 5662 "/opt/smp86xx/smp86xx_toolchain_2.8.2.0/toolchain_build_mipsel_nofpu/gdb-6.5/sim/mips/mips.igen"
  itable_TLBWR_COP0,
  nr_itable_entries,
} itable_index;

typedef enum {
  itable_flag_32,
  itable_flag_f,
  nr_itable_flags,
} itable_flags;
extern const char *itable_flag_names[];

typedef enum {
  nr_itable_options,
} itable_options;
extern const char *itable_option_names[];

typedef enum {
  itable_processor_dsp,
  itable_processor_mdmx,
  itable_processor_mips16,
  itable_processor_mips16e,
  itable_processor_mips32,
  itable_processor_mips32r2,
  itable_processor_mips3d,
  itable_processor_mips64,
  itable_processor_mips64r2,
  itable_processor_mipsI,
  itable_processor_mipsII,
  itable_processor_mipsIII,
  itable_processor_mipsIV,
  itable_processor_mipsV,
  itable_processor_r3900,
  itable_processor_sb1,
  itable_processor_vr4100,
  itable_processor_vr4120,
  itable_processor_vr5000,
  itable_processor_vr5400,
  itable_processor_vr5500,
  nr_itable_processors,
} itable_processors;
extern const char *itable_processor_names[];

typedef struct _itable_instruction_info {
  itable_index nr;
  char *format;
  char *form;
  char *flags;
  char flag[nr_itable_flags + 1];
  char *options;
  char option[nr_itable_options + 1];
  char *processors;
  char processor[nr_itable_processors + 1];
  char *name;
  char *file;
  int line_nr;
} itable_info;

extern itable_info itable[nr_itable_entries];

enum {
  sizeof_itable_form = 8,
  sizeof_itable_name = 12,
  sizeof_itable_file = 10,
};

#endif /* _ITABLE_H_*/
