/* This file is part of GDB.

   Copyright 2002 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
 
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.

   --

   This file was generated by the program igen */

#ifndef SEMANTICS_H
#define SEMANTICS_H

typedef instruction_address idecode_semantic
(SIM_DESC sd,
 idecode_cache *cache_entry,
 instruction_address cia);

typedef instruction_address idecode_semantic_0
(SIM_DESC sd,
 instruction_address cia);

typedef instruction_address idecode_semantic_1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);


EXTERN_SEMANTICS\
(instruction_address) semantic_RSVD_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SYSCALL_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BREAK_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TGE_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TGEU_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLT_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLTU_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TEQ_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TNE_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SLLV_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SRLV_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SRAV_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MOVZ_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MOVN_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ADD_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ADDU_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SUB_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SUBU_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_AND_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_OR_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_XOR_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_NOR_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SLT_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SLTU_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MULT_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MULTU_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_DIV_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_DIVU_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MOVtf_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_JALR_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_JR_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MTHI_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MTLO_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SLLa_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SRL_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SRA_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MFHI_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MFLO_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SYNC_SPECIAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BLTZ_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BGEZ_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BLTZL_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BGEZL_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TGEI_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TGEIU_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLTI_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLTIU_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TEQI_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TNEI_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BLTZAL_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BGEZAL_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BLTZALL_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BGEZALL_REGIMM
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_J_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_JAL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BEQ_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BNE_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BLEZ_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BGTZ_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ADDI_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ADDIU_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SLTI_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SLTIU_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ANDI_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ORI_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_XORI_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LUI_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_COPz_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MFC0_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MTC0_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BC0F_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BC0T_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BC0FL_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BC0TL_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLBR_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLBWI_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLBWR_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TLBP_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_RFE_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ERET_COP0
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MFC1b_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_CFC1b_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MTC1b_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_CTC1b_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BC1b_COP1S
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ADD_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SUB_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MUL_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_DIV_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MOVZ_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MOVN_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_C_cond_fmtb_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MOVtf_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SQRT_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ABS_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_MOV_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_NEG_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ROUND_W_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_TRUNC_W_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_CEIL_W_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_FLOOR_W_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_RECIP_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_RSQRT_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_CVT_S_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_CVT_D_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_CVT_W_fmt_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SWXC1_COP1X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BEQL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BNEL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BLEZL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_BGTZL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LB_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LH_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LWL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LW_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LBU_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LHU_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LWR_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SB_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SH_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SWL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SW_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SWR_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_CACHE_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LWCz_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LL_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LWC1_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_PREF_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_LDC1b_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SWCz_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SC_NORMAL
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SWC1_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_SDC1b_COP1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

#endif /* _SEMANTICS_H_*/
